### ISSUE TITLE
compilation problem on Mac 10.12.6

### ISSUE THREAD

**Issue by emicklei** [youpy/go-coremidi#5]
```
/github.com/youpy/go-coremidi/util.go:17:38: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCString
```
let me know if you need more info from my system to help you find a solution.

go version go1.14 darwin/amd64

**Comment by emicklei** [comment]
this can be solved by using `C.kCFAllocatorDefault` instead of passing nil

**Comment by youpy** [comment]
Thanks! fixed
