### ISSUE TITLE
problem with two sources with the same name

### ISSUE THREAD

**Issue by surrain** [youpy/go-coremidi#6]
When I run midirouter without a config file, it shows me my available inputs. Two of them have the same name of "KEYBOARD". I can use "KEYBOARD" as a SourceDevice in my config to set one of them as the input, but I can't differentiate between them. One is a microKEY2 Air 49 and the other is a microKEY2 Air 37. I've tried entering the source name different ways, but nothing other than just entering "KEYBOARD" as the SourceDevice works.

**Comment by youpy** [comment]
When you say midirouter do you mean https://github.com/youpy/go-coremidi/blob/master/examples/forwarder/forwarder.go ?
If so, you can specify the device name with the following changes:

```diff
diff --git a/examples/forwarder/forwarder.go b/examples/forwarder/forwarder.go
index 000119d..892fd24 100644
--- a/examples/forwarder/forwarder.go
+++ b/examples/forwarder/forwarder.go
@@ -9,10 +9,10 @@ import (
 )
 
 func main() {
-	var sourceName string
+	var deviceName string
 	var destinationName string
 
-	flag.StringVar(&sourceName, "source", "KEYBOARD", "source name")
+	flag.StringVar(&deviceName, "device", "microKEY-25", "device name")
 	flag.StringVar(&destinationName, "destination", "UM-ONE", "destination name")
 	flag.Parse()
 
@@ -51,7 +51,7 @@ func main() {
 	}
 
 	for _, source := range sources {
-		if source.Name() == sourceName {
+		if source.Entity().Device().Name() == deviceName {
 			port.Connect(source)
 		}
 	}
```

**Comment by youpy** [comment]
midirouter is https://github.com/NothNoth/MIDIRouter/blob/main/cmd/midirouter/midirouter.go, I just found it!
Could you ask the author of midirouter?

**Comment by surrain** [comment]
Thanks, I will.
